// Fixed-point, piecewise-linear sigmoid approximation.
//
// Default implementation parameters are generated by
// scripts/sigmoid_pwl_uniform_continuous.py:
//   * input/output: signed Q4.12
//   * coefficients: signed Q2.14
//   * right-half segments: 40, uniformly spaced over [0, 8]
//   * symmetry: sigmoid(-x) = 1 - sigmoid(x)
//
// The coefficient table is fixed for the default 16-bit formats and 40
// segments.  If DATA_WIDTH, fractional-bit parameters, or SEGMENT_COUNT are
// changed, regenerate the coefficient table before using the resulting RTL.
// The block is combinational: y_out changes with x_in in the same cycle.

module sigmoid_cell #(
    parameter integer DATA_WIDTH           = 16,
    parameter integer DATA_FRACTIONAL_BITS = 12,
    parameter integer COEFF_WIDTH          = 16,
    parameter integer COEFF_FRACTIONAL_BITS = 14,
    parameter integer SEGMENT_COUNT        = 40,
    // In Q4.12, 8.0 is raw 32768.  Strict saturation matches the Python model:
    // abs(x) > SATURATION_RAW, rather than abs(x) >= SATURATION_RAW.
    parameter [DATA_WIDTH:0] SATURATION_RAW = 17'd32768,
    parameter integer SATURATION_INCLUSIVE  = 0
) (
    input  wire signed [DATA_WIDTH-1:0] x_in,
    output reg        [DATA_WIDTH-1:0] y_out
);

    localparam integer PRODUCT_WIDTH = DATA_WIDTH + DATA_WIDTH + 1;
    localparam integer OUTPUT_ONE_RAW = (1 << DATA_FRACTIONAL_BITS);
    localparam integer PRODUCT_SHIFT = COEFF_FRACTIONAL_BITS;
    localparam integer INTERCEPT_SHIFT = COEFF_FRACTIONAL_BITS - DATA_FRACTIONAL_BITS;
    localparam signed [PRODUCT_WIDTH-1:0] PRODUCT_ROUND_BIAS =
        ({{(PRODUCT_WIDTH-1){1'b0}}, 1'b1} <<< (PRODUCT_SHIFT - 1));
    localparam signed [COEFF_WIDTH:0] INTERCEPT_ROUND_BIAS =
        ({{COEFF_WIDTH{1'b0}}, 1'b1} <<< (INTERCEPT_SHIFT - 1));

    // One extra bit is essential: abs(16'sh8000) is 32768, not 16 bits.
    reg [DATA_WIDTH:0] magnitude;
    reg [5:0] segment_index;
    reg signed [COEFF_WIDTH-1:0] slope_q2_14;
    reg signed [COEFF_WIDTH-1:0] intercept_q2_14;
    reg signed [PRODUCT_WIDTH-1:0] product_q2_26;
    reg signed [PRODUCT_WIDTH-1:0] scaled_product_q4_12;
    reg signed [COEFF_WIDTH:0] scaled_intercept_q4_12;
    reg signed [PRODUCT_WIDTH-1:0] line_value_q4_12;
    reg [DATA_WIDTH-1:0] positive_value;

    always @* begin
        // Convert x to a non-negative Q4.12 magnitude using a widened result.
        if (x_in[DATA_WIDTH-1])
            magnitude = {1'b0, (~x_in + {{(DATA_WIDTH-1){1'b0}}, 1'b1})};
        else
            magnitude = {1'b0, x_in};

        // Python uses searchsorted(..., side="right"): an exact internal
        // boundary belongs to the segment on its right.
        if      (magnitude < 17'd819)   segment_index = 6'd0;
        else if (magnitude < 17'd1638)  segment_index = 6'd1;
        else if (magnitude < 17'd2458)  segment_index = 6'd2;
        else if (magnitude < 17'd3277)  segment_index = 6'd3;
        else if (magnitude < 17'd4096)  segment_index = 6'd4;
        else if (magnitude < 17'd4915)  segment_index = 6'd5;
        else if (magnitude < 17'd5734)  segment_index = 6'd6;
        else if (magnitude < 17'd6554)  segment_index = 6'd7;
        else if (magnitude < 17'd7373)  segment_index = 6'd8;
        else if (magnitude < 17'd8192)  segment_index = 6'd9;
        else if (magnitude < 17'd9011)  segment_index = 6'd10;
        else if (magnitude < 17'd9830)  segment_index = 6'd11;
        else if (magnitude < 17'd10650) segment_index = 6'd12;
        else if (magnitude < 17'd11469) segment_index = 6'd13;
        else if (magnitude < 17'd12288) segment_index = 6'd14;
        else if (magnitude < 17'd13107) segment_index = 6'd15;
        else if (magnitude < 17'd13926) segment_index = 6'd16;
        else if (magnitude < 17'd14746) segment_index = 6'd17;
        else if (magnitude < 17'd15565) segment_index = 6'd18;
        else if (magnitude < 17'd16384) segment_index = 6'd19;
        else if (magnitude < 17'd17203) segment_index = 6'd20;
        else if (magnitude < 17'd18022) segment_index = 6'd21;
        else if (magnitude < 17'd18842) segment_index = 6'd22;
        else if (magnitude < 17'd19661) segment_index = 6'd23;
        else if (magnitude < 17'd20480) segment_index = 6'd24;
        else if (magnitude < 17'd21299) segment_index = 6'd25;
        else if (magnitude < 17'd22118) segment_index = 6'd26;
        else if (magnitude < 17'd22938) segment_index = 6'd27;
        else if (magnitude < 17'd23757) segment_index = 6'd28;
        else if (magnitude < 17'd24576) segment_index = 6'd29;
        else if (magnitude < 17'd25395) segment_index = 6'd30;
        else if (magnitude < 17'd26214) segment_index = 6'd31;
        else if (magnitude < 17'd27034) segment_index = 6'd32;
        else if (magnitude < 17'd27853) segment_index = 6'd33;
        else if (magnitude < 17'd28672) segment_index = 6'd34;
        else if (magnitude < 17'd29491) segment_index = 6'd35;
        else if (magnitude < 17'd30310) segment_index = 6'd36;
        else if (magnitude < 17'd31130) segment_index = 6'd37;
        else if (magnitude < 17'd31949) segment_index = 6'd38;
        else                         segment_index = 6'd39;

        // Q2.14 coefficients from outputs/hardware/sigmoid_uniform_40seg.json.
        case (segment_index)
            6'd0:  begin slope_q2_14 = 16'sd4089; intercept_q2_14 = 16'sd8192;  end
            6'd1:  begin slope_q2_14 = 16'sd4018; intercept_q2_14 = 16'sd8204;  end
            6'd2:  begin slope_q2_14 = 16'sd3848; intercept_q2_14 = 16'sd8272;  end
            6'd3:  begin slope_q2_14 = 16'sd3651; intercept_q2_14 = 16'sd8388;  end
            6'd4:  begin slope_q2_14 = 16'sd3374; intercept_q2_14 = 16'sd8608;  end
            6'd5:  begin slope_q2_14 = 16'sd3062; intercept_q2_14 = 16'sd8920;  end
            6'd6:  begin slope_q2_14 = 16'sd2759; intercept_q2_14 = 16'sd9284;  end
            6'd7:  begin slope_q2_14 = 16'sd2445; intercept_q2_14 = 16'sd9724;  end
            6'd8:  begin slope_q2_14 = 16'sd2149; intercept_q2_14 = 16'sd10196; end
            6'd9:  begin slope_q2_14 = 16'sd1855; intercept_q2_14 = 16'sd10724; end
            6'd10: begin slope_q2_14 = 16'sd1591; intercept_q2_14 = 16'sd11252; end
            6'd11: begin slope_q2_14 = 16'sd1367; intercept_q2_14 = 16'sd11744; end
            6'd12: begin slope_q2_14 = 16'sd1153; intercept_q2_14 = 16'sd12256; end
            6'd13: begin slope_q2_14 = 16'sd980;  intercept_q2_14 = 16'sd12704; end
            6'd14: begin slope_q2_14 = 16'sd804;  intercept_q2_14 = 16'sd13196; end
            6'd15: begin slope_q2_14 = 16'sd680;  intercept_q2_14 = 16'sd13568; end
            6'd16: begin slope_q2_14 = 16'sd566;  intercept_q2_14 = 16'sd13932; end
            6'd17: begin slope_q2_14 = 16'sd467;  intercept_q2_14 = 16'sd14268; end
            6'd18: begin slope_q2_14 = 16'sd401;  intercept_q2_14 = 16'sd14504; end
            6'd19: begin slope_q2_14 = 16'sd304;  intercept_q2_14 = 16'sd14872; end
            6'd20: begin slope_q2_14 = 16'sd278;  intercept_q2_14 = 16'sd14976; end
            6'd21: begin slope_q2_14 = 16'sd202;  intercept_q2_14 = 16'sd15296; end
            6'd22: begin slope_q2_14 = 16'sd190;  intercept_q2_14 = 16'sd15348; end
            6'd23: begin slope_q2_14 = 16'sd131;  intercept_q2_14 = 16'sd15620; end
            6'd24: begin slope_q2_14 = 16'sd136;  intercept_q2_14 = 16'sd15596; end
            6'd25: begin slope_q2_14 = 16'sd91;   intercept_q2_14 = 16'sd15820; end
            6'd26: begin slope_q2_14 = 16'sd97;   intercept_q2_14 = 16'sd15788; end
            6'd27: begin slope_q2_14 = 16'sd57;   intercept_q2_14 = 16'sd16004; end
            6'd28: begin slope_q2_14 = 16'sd55;   intercept_q2_14 = 16'sd16016; end
            6'd29: begin slope_q2_14 = 16'sd38;   intercept_q2_14 = 16'sd16116; end
            6'd30: begin slope_q2_14 = 16'sd34;   intercept_q2_14 = 16'sd16140; end
            6'd31: begin slope_q2_14 = 16'sd20;   intercept_q2_14 = 16'sd16228; end
            6'd32: begin slope_q2_14 = 16'sd27;   intercept_q2_14 = 16'sd16184; end
            6'd33: begin slope_q2_14 = 16'sd4;    intercept_q2_14 = 16'sd16336; end
            6'd34: begin slope_q2_14 = 16'sd26;   intercept_q2_14 = 16'sd16188; end
            6'd35: begin slope_q2_14 = -16'sd8;   intercept_q2_14 = 16'sd16428; end
            6'd36: begin slope_q2_14 = 16'sd10;   intercept_q2_14 = 16'sd16300; end
            6'd37: begin slope_q2_14 = 16'sd26;   intercept_q2_14 = 16'sd16180; end
            6'd38: begin slope_q2_14 = 16'sd5;    intercept_q2_14 = 16'sd16336; end
            default: begin slope_q2_14 = 16'sd20;  intercept_q2_14 = 16'sd16220; end
        endcase

        // slope(Q2.14) * magnitude(Q4.12) is Q6.26.  Round it to Q4.12
        // using the same ties-away-from-zero rule as the Python model.
        product_q2_26 = slope_q2_14 * $signed(magnitude);
        if (product_q2_26 < 0)
            scaled_product_q4_12 = -(((-product_q2_26 + PRODUCT_ROUND_BIAS) >>> PRODUCT_SHIFT));
        else
            scaled_product_q4_12 = (product_q2_26 + PRODUCT_ROUND_BIAS) >>> PRODUCT_SHIFT;

        // Every generated intercept is an exact multiple of four, but the
        // rounding expression preserves the Python model for future tables.
        if (intercept_q2_14 < 0)
            scaled_intercept_q4_12 =
                -(((-intercept_q2_14 + INTERCEPT_ROUND_BIAS) >>> INTERCEPT_SHIFT));
        else
            scaled_intercept_q4_12 =
                (intercept_q2_14 + INTERCEPT_ROUND_BIAS) >>> INTERCEPT_SHIFT;

        line_value_q4_12 = scaled_product_q4_12 + scaled_intercept_q4_12;
        if (line_value_q4_12 <= 0)
            positive_value = {DATA_WIDTH{1'b0}};
        else if (line_value_q4_12 >= OUTPUT_ONE_RAW)
            positive_value = OUTPUT_ONE_RAW[DATA_WIDTH-1:0];
        else
            positive_value = line_value_q4_12[DATA_WIDTH-1:0];

        // Saturation is applied before mirroring.  At the default +8 limit,
        // strict saturation is unreachable for a signed Q4.12 input; -8 is
        // still evaluated by the final PWL segment, exactly as in Python.
        if ((SATURATION_INCLUSIVE && (magnitude >= SATURATION_RAW)) ||
            (!SATURATION_INCLUSIVE && (magnitude > SATURATION_RAW))) begin
            if (x_in[DATA_WIDTH-1])
                y_out = {DATA_WIDTH{1'b0}};
            else
                y_out = OUTPUT_ONE_RAW[DATA_WIDTH-1:0];
        end else if (x_in[DATA_WIDTH-1]) begin
            y_out = OUTPUT_ONE_RAW[DATA_WIDTH-1:0] - positive_value;
        end else begin
            y_out = positive_value;
        end
    end

endmodule
